# Prometheus configuration for Mechanical Integrity AI System
# Monitors all services and safety-critical metrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mechanical-integrity-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Mechanical Integrity API
  - job_name: 'mechanical-integrity-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    
    # Custom labels for safety-critical system
    labels:
      service: 'mechanical-integrity-api'
      environment: 'production'
      safety_critical: 'true'
      compliance: 'api-579'

  # PostgreSQL database metrics (using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    labels:
      service: 'postgresql'
      component: 'database'

  # Redis metrics (using redis_exporter) 
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    labels:
      service: 'redis'
      component: 'cache'

  # Nginx metrics (using nginx-prometheus-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    labels:
      service: 'nginx'
      component: 'proxy'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    labels:
      service: 'node-exporter'
      component: 'system'

  # Docker container metrics (using cadvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    labels:
      service: 'cadvisor'
      component: 'containers'

  # Health checks for all services
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'api:8000'
        - 'postgres:5432'
        - 'redis:6379'
        - 'ollama:11434'
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s
    labels:
      monitoring_type: 'health_check'