"""Fix assumptions field to allow NULL values

Revision ID: 37494688822b
Revises: 78def87bc56b
Create Date: 2025-08-21 15:56:12.136239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37494688822b'
down_revision: Union[str, None] = '78def87bc56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix assumptions field to allow NULL values for safety-critical calculations
    op.alter_column('api579_calculations', 'assumptions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_comment='List of assumptions made in calculations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert assumptions field back to NOT NULL constraint
    op.alter_column('api579_calculations', 'assumptions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_comment='List of assumptions made in calculations')
    # Note: Not recreating dropped tables as they were cleanup from previous schema
    # ### end Alembic commands ###
