"""Convert Equipment model Float columns to DECIMAL for safety-critical precision

Revision ID: 78def87bc56b
Revises: 6e891b920f50
Create Date: 2025-08-21 15:43:45.356693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78def87bc56b'
down_revision: Union[str, None] = '6e891b920f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert Float columns to DECIMAL for safety-critical precision
    op.alter_column('equipment', 'design_pressure',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=8, scale=2),
               existing_comment='Design pressure in PSI - used for MAWP calculations',
               existing_nullable=False)
    op.alter_column('equipment', 'design_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=6, scale=1),
               existing_comment='Design temperature in °F - affects material properties',
               existing_nullable=False)
    op.alter_column('equipment', 'design_thickness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=6, scale=3),
               existing_comment='Original design thickness in inches - baseline for remaining life',
               existing_nullable=False)
    op.alter_column('equipment', 'corrosion_allowance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=5, scale=3),
               existing_comment='Design corrosion allowance in inches (typically 0.125)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert DECIMAL columns back to DOUBLE_PRECISION
    op.alter_column('equipment', 'corrosion_allowance',
               existing_type=sa.DECIMAL(precision=5, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Design corrosion allowance in inches (typically 0.125)',
               existing_nullable=False)
    op.alter_column('equipment', 'design_thickness',
               existing_type=sa.DECIMAL(precision=6, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Original design thickness in inches - baseline for remaining life',
               existing_nullable=False)
    op.alter_column('equipment', 'design_temperature',
               existing_type=sa.DECIMAL(precision=6, scale=1),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Design temperature in °F - affects material properties',
               existing_nullable=False)
    op.alter_column('equipment', 'design_pressure',
               existing_type=sa.DECIMAL(precision=8, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Design pressure in PSI - used for MAWP calculations',
               existing_nullable=False)
    # Note: Not recreating dropped tables as they were cleanup from previous schema
    # ### end Alembic commands ###
